export enum ApiFilters {
  PAGE = 'page',
  PAGESIZE = 'pagesize',
  SORT = 'sort',
  ANSWERS = 'answers',
  ORDER = 'order',
  QUERY = 'q',
  VIEWS = 'views',
  TITLE = 'title',
  BODY = 'body',
  CLOSED = 'closed',
  URL = 'url',
  ACCEPTED = 'accepted',
  TAGGED = 'tagged',
  NOTTAGGED = 'nottagged',
  MIGRATED = 'migrated',
  MIN = 'min',
  MAX = 'max',
  FROMDATE = 'fromdate',
  TODATE = 'todate',
  WIKI = 'wiki'
}